version: '3'
services:
  mysql:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "1234567890"
      MYSQL_DATABASE: pessoa
    volumes:
      - C:\Users\Nova\Documents\Nova Tendencia\EMISSAO JAVA\rinha\my-custom.cnf:/etc/mysql/conf.d/my-custom.cnf
    networks:
      - my_network
    deploy:
      resources:
        limits:
          cpus: '0.32'
          memory: 768m
        reservations:
          cpus: '0.10'
          memory: 192m

networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.0.0/24
