version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Monta o arquivo nginx.conf no contêiner
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 256m
        reservations:
          cpus: '0.023'
          memory: 64mb
    networks:
      my_network:
        ipv4_address: 172.23.0.10
        aliases:
          - api
    hostname: nginx
    extra_hosts:
      - "api:172.23.0.10"
      - "api:127.0.0.1"
    depends_on:
      - app1
      - app2

  app1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/pessoa
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234567890
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
      SPRING_APPLICATION_NAME: pessoa-ms
    networks:
      - my_network
    deploy:
      resources:
        limits:
          cpus: '0.49'
          memory: 1g
        reservations:
          cpus: '0.125'
          memory: 257mb
    hostname: app1

  app2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/pessoa
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234567890
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
      SPRING_APPLICATION_NAME: pessoa-ms
    networks:
      - my_network
    deploy:
      resources:
        limits:
          cpus: '0.49'
          memory: 1g
        reservations:
          cpus: '0.125'
          memory: 257mb
    hostname: app2

networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.0.0/24
