version: '3'
services:
  haproxy:
    image: haproxy:latest
    ports:
      - "80:80"
    volumes:
      - C:\Users\Nova\Documents\Nova Tendencia\EMISSAO JAVA\rinha\haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256m

  app1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/pessoa
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234567890
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
      SPRING_APPLICATION_NAME: pessoa-ms
    networks:
      - default
    deploy:
      resources:
        limits:
          cpus: '0.375'
          memory: 1g
    hostname: app1

  app2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/pessoa
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234567890
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
      SPRING_APPLICATION_NAME: pessoa-ms
    networks:
      - default
    deploy:
      resources:
        limits:
          cpus: '0.375'
          memory: 1g
    hostname: app2

networks:
  default:
